# Generated by Django 4.2.6 on 2023-10-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0003_alter_readingsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingsession',
            unique_together=set(),
        ),
    ]
