# Generated by Django 4.2.6 on 2023-10-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0005_alter_readingsession_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readingsession',
            unique_together=set(),
        ),
    ]
