# Generated by Django 4.2.6 on 2023-10-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_reading_time_30_days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_reading_time_7_days',
            field=models.FloatField(default=0),
        ),
    ]
